### ISSUE TITLE
Subscribing VPC not Working

### ISSUE THREAD

**Issue by deanlee1** [PaloAltoNetworks/aws-transit-vpc#15]
Hello,

I have run the InitializeTransitAccount and InitializeSubscriberAccount without issue (no VPC created).  However, when adding subscribing VPC's, I am running into the following issues:

1) When subscribing an existing VPC using the tag, the firewalls get created (PaGroup58), but the VPN connections never get created.  These firewalls are properly bootstrapped (PW from the deployment guide works).

2) When using the CFT to create a new VPC, a new set of firewalls gets built (PaGroup29), but again the VPN connections never get created.  The new firewalls are NOT properly bootstrapped.

I had previously run the InitializeSubscriberAccount and created a VPC at the same time (option 8.1).  This worked and created the VPN connections.

Could you provide information on how to fix this issue?

**Comment by narayan-iyengar** [comment]
@deanlee1 

1. Does your existing VPC have a VGW? The automation requires that no VGW be present...as it creates one for you. Apart from that make sure that you specify the account numbers correctly when deploying the initializer CFTs.

2. Are you using the same bootstrap bucket.


Lastly I just realized I had never merged a recent change to make the default fw instance m4.xlarge 

This could cause issues..I just update the branch so please resend and try again and let me know

**Comment by deanlee1** [comment]
No it does not have a VGW.  Also, when I created the VPC using the CFT, it also did not create a VGW.

yes.  for the bootstrap bucket

I changed the json to default to m4.4xlarge.

**Comment by narayan-iyengar** [comment]
Is this cross account or same account?

you can navigate to the step functions console and find the logs  [for the subscribing vpc] where it is failing. That will give you an idea of where to start poking around.

**Comment by deanlee1** [comment]
same account.  I'll check to see what they say.

**Comment by narayan-iyengar** [comment]
ok...keep me posted.

**Comment by deanlee1** [comment]
<img width="1166" alt="steps" src="https://user-images.githubusercontent.com/38502869/38947768-c651ac44-430b-11e8-9591-6eefbc368f24.PNG">

I'm not 100% sure, but it seems like the lamba function correctly identifies the subscribing (existing VPC), but then just stalls when trying to create the VPN connection.  In addition, I can't tell why it decided to create a new pagroup instead of using the existing one.  It also looks like the transitvpc had trouble connecting to dynamodb

**Comment by deanlee1** [comment]
Hi,

So I removed all the CFT's and redid them and now everything seems to be working properly.  2 things to note, though.

1) I forgot to type the string in for the DeLicenseApiKey field.  This seemed to cause issues.

2) I had run the CFT's and removed them a couple times.  One thing that I did before this previous time was delete all the old CloudWatch logs prior to rerunning the CFT's.  Not sure if that helped, but I think it did.

I'm still getting errors on the State Functions, but the VPN's successfully created for both a new VPC and an existing VPC.  Not sure if it matters or not but I also put "YES" as opposed to "Yes" for the subscribingVPC tag.

Thanks

**Comment by rr128** [comment]
Can you go into detail about step #2??  We are running into the same issue, no creation of vpn tunnels or vgw.

**Comment by deanlee1** [comment]
If you go to your CloudWatch logs, you'll see a lot of logs that have a name ending in the transit or subscription cft stacks that you ran.  For example, for a transit vpc, if the stack was labeled "transit vpc", you would see logs that end in "- transit vpc."

I deleted all these logs in CloudWatch, then deleted all the cft stacks, then reran the stacks.  Everything seemed to work correctly after that.

**Comment by rr128** [comment]
Thanks.  I will try that out and let you guys know the results.

**Comment by rr128** [comment]
That worked.  Thanks!
