### ISSUE TITLE
Management interface is attached to elastic IP, PA did not recognize two NICs

### ISSUE THREAD

**Issue by Schizamp** [PaloAltoNetworks/aws-transit-vpc#39]
Wondering if anyone else is seeing this, am following the documentation closely. Was able to run the CFTs and link a subscriber VPC. The PAGroup template ran, spun up two nodes with two ENIs, one in an untrust subnet with elastic IP attached, another in a trusted subnet. When I log into the Palo Alto device, it has only recognized one interface, the public interface, and has associated management to it. I can browse to the web UI from the internet.

![image](https://user-images.githubusercontent.com/35105617/44092517-aa66f47c-9f9e-11e8-96fa-29a2f026470b.png)

**Comment by narayan-iyengar** [comment]
Try rebooting the firewall..and see if that helps

--
/narayan

**Comment by Schizamp** [comment]
Will try that. Also found that in the Powerpoint deployment guide, it says to "Verify FW1 Interfaces and default route. Double check that your e1/1 has the correct IP/Mask." Since mine does not, it only has the secondary ENI IP that has the EIP attached, I'm guessing I need to change this. It seems odd to call it out specifically in the deployment guide if there wasn't an issue with this.

**Comment by Schizamp** [comment]
The second interface did not light up. @narayan-iyengar did you experience the same issue or have to update the IP/mask on eth1/1?

**Comment by narayan-iyengar** [comment]
Never seen this issue. Was just a guess.

Do you have two enis ?


--
Thanks,
/narayan
________________________________

**Comment by Schizamp** [comment]
Found out that the management interface (eth0) is not listed on this page, it's under Devices > Interfaces. I removed the Management Profile DataPlane from eth1 and was able to make the management interface private. I think this was more of an issue of me not being a network guy or knowing Palo Alto. I'll go ahead and close.
