### ISSUE TITLE
2x Transit VPCs in the same account?

### ISSUE THREAD

**Issue by Schizamp** [PaloAltoNetworks/aws-transit-vpc#40]
I have built a Lab Transit VPC + Sub config and am planning to add Non-Lab Transit VPC + Subs config. I'd like to use the same account for both Transit VPCs. Has anyone tried this? I would prefer not to break the existing Transit-Lab by standing up another, hoping that someone has tried this before.

Cross posted from Live.

**Comment by narayan-iyengar** [comment]
It won't work...I think it was posted ion live as well.

Things will get very messy as the scripts are not designed to run two transit VPC hubs in the same account

**Comment by Schizamp** [comment]
You're right. The PA group number is hardcoded. I have to tear it all down and rebuild in a new account.
