### ISSUE TITLE
CF JSON to YML?

### ISSUE THREAD

**Issue by gliptak** [PaloAltoNetworks/aws-transit-vpc#63]
Would there be an interest in a PR converting https://github.com/PaloAltoNetworks/aws-transit-vpc/tree/master/cfts/*.json to *.yml?

https://github.com/PaloAltoNetworks/aws-transit-vpc/issues/52

**Comment by gliptak** [comment]
@jpeezus please comment. Somebody would also need to update the PDFs (as sources to generate from weren't made available)

**Comment by jpeezus** [comment]
@gliptak At this point in time I would say no. We have a team that converts or creates templates in the language of our focus. Right now although YML is very popular we don't have plans to convert this to YML or update any documentation based on any outside conversions. That could change in the future. We appreciate your feedback and interaction and look forward to continuing the interaction.

**Comment by gliptak** [comment]
@jpeezus thank you for the details

**Comment by panwce** [comment]
You can flip between json and yaml using cfn-flip
I have "flipped" this template in the past without issues
https://github.com/awslabs/aws-cfn-template-flip
https://cfnflip.com/

**Comment by gliptak** [comment]
@panwce thank you for the pointer. The thought here is that YAML is friendlier to source control diffs allowing to understand update impact quicker.
